package com.fluffy.universe.recordplay;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class LoginTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {

        System.setProperty("webdriver.chrome.driver", "C:\\Users\\EduardBryzhko\\IdeaProjects\\universe-master\\src\\test\\java\\com\\fluffy\\universe\\recordplay\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void login() {
        driver.get("http://127.0.0.1:8080/");
        driver.manage().window().setSize(new Dimension(1500, 1050));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.id("sign-in__email")).sendKeys("beasumy+q@gmail.com");
        driver.findElement(By.id("sign-in__password")).sendKeys("82Gerko!");
        driver.findElement(By.cssSelector(".form__button")).click();
        driver.findElement(By.className("dropdown__icon")).isDisplayed();
    }

    @Test
    public void loginWithIncorrrectPassword() {
        driver.get("http://127.0.0.1:8080/");
        driver.manage().window().setSize(new Dimension(1200, 1050));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.id("sign-in__email")).sendKeys("beasumy+q@gmail.com");
        driver.findElement(By.id("sign-in__password")).sendKeys("qwerty");
        driver.findElement(By.cssSelector(".sign-in-form")).click();
        driver.findElement(By.cssSelector(".alert__inner")).isDisplayed();
    }

    @Test
    public void loginWithEmptyPasswordField() {
        driver.get("http://127.0.0.1:8080/");
        driver.manage().window().setSize(new Dimension(1200, 1050));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.id("sign-in__email")).sendKeys("beasumy+q@gmail.com");
        driver.findElement(By.cssSelector(".sign-in-form")).click();
        driver.findElement(By.cssSelector(".form__feedback")).isDisplayed();
    }
}
